### PR TITLE
[Fix #128] Fix alert after donation is updated

### LINKED ISSUE #128: Fix  alert after donation is successfully created

### PR DESCRIPTION
**Pull request by limxinyuuu**
This change fixes the bug that flash message after donation is updated is not green.

Before:
image

After:
image

---

**Before submitting, check that:**

 - [ ] You have added (passing) tests for your code.
 - [ ] You have written good* commit messages.
 - [ ] You have squashed relevant commits together.
 - [ ] You have ensured that RuboCop is passing.
 - [ ] Your PR relates to one subject, with a clear title and
       description using complete, grammatically correct sentences.

---

If your change contains views, ensure that:

 - [ ] You have included a screenshot of the new view.

---

*If you do not know what makes a good commit message, or why it
is important, please refer to these resources: [1][1], [2][2], [3][3].

[1]: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
[2]: http://chris.beams.io/posts/git-commit/
[3]: https://github.com/blog/1943-how-to-write-the-perfect-pull-request

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -1,4 +1,6 @@
 class ApplicationController < ActionController::Base
+  add_flash_types :warning, :error, :success
```
Comment (Drenmi) [inline app/controllers/application_controller.rb]: Today I learned. 😀

**Comment by Drenmi** [comment]
🌻
